### ISSUE TITLE
我在window 下运行出现了这种情况。使用了 python test.py --exp_name DIFNet_lrp --mode difnet_lrp命令行

### ISSUE THREAD

**Issue by 775266553** [mrwu-mac/DIFNet#11]
Evaluation:   0%|                                                                            | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 141, in <module>
    scores = predict_captions(model, dict_dataloader_test, text_field, out_file)
  File "test.py", line 31, in predict_captions
    for it, ((img_id, images, pixels), caps_gt) in enumerate(iter(dataloader)):
  File "C:\Users\77526\miniconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\77526\miniconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\77526\miniconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 56, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
TypeError: 'generator' object is not callable

**Comment by 0xzzq666** [comment]
您好？请问问题解决了吗
